### ISSUE TITLE
problem in group res_process

### ISSUE THREAD

**Issue by leohank** [ChiLiubio/microeco#10]
Hi, 
How can I get  res_process for different groups in trans_nullmodel class?

it seems I get the overall process for all samples using cal process and res_process directly.

Thanks

**Comment by ChiLiubio** [comment]
@leohank The best way I think is to create microtable object seperately and run the functions you need in trans_nullmodel. The pseudo code is like this:
`data(dataset)

group1 <- clone(dataset)
group1$sample_table <- subset(group1$sample_table, Group == "IW")
group1$tidy_dataset()

group2 <- clone(dataset)
group2$sample_table <- subset(group2$sample_table, Group == "CW")
group2$tidy_dataset()
`
Then you can run trans_nullmodel for group1 and group2, respectively.

**Comment by leohank** [comment]
If species in different sites may be from one big species pool, as you described, the process was separately evaluated，do you think it will affect the results? 
As mentioned in the tutorial, if we perform null model analysis for each group individually, it obtained different results when compared to perform for all samples.

**Comment by ChiLiubio** [comment]
It depends. Let's imagine two extreme cases. 1: one field sampling area is far away from another. The null hypothesis may be related with two species pool and local processes may be more important than regional processes under this situation. This case is also suitable for the treatment experiments. So using the methods you said are obviously reasonable. 2: all samples come from one big species pool we recognized. Now what is the reason you split the samples arbitrarilly into different groups? Generally, if you do this, you have some a priori experience on the study. Otherwise, it is hard to explain why different groups exist. So the key point I think is whether the null hypothesis is reasonable.

**Comment by leohank** [comment]
I agree with you that the reasonable null hypothesis is important. now I have a case, we study the microbial community colonized on the surface of tissues of mussel. these mussels are cultivated in natural field. so we assume these microbial compositions are from seawater. I wonder which method is more reasonable. do you think these species are from the same pool. 
If evaluate the ecological process as you suggested, should I also measured the βNTI separately?

**Comment by ChiLiubio** [comment]
From what you provided, it is still hard for me to make sure the reasonable metric and null hypothesis. Those should be context-dependent and included in an integrate story.
