### ISSUE TITLE
Problem of cal_tax4fun2_FRI ()

### ISSUE THREAD

**Issue by Wellington9023** [ChiLiubio/microeco#142]
Hi,

Thanks for your great package!

After runing the t1$cal_tax4fun2, I run t1$cal_tax4fun2_FRI(), but there is an error " please  first run cal_tax4fun2 ". I check the code and find res_tax4fun2_reference_profile was not kept in t1 project. And rep_fasta_16S data was deleted in this version. Could you please fix the code and upload the data? Thank you very much!

**Comment by ChiLiubio** [comment]
Hi.

I guess the cal_taxfun2 function did not run correctly. Please use the example dataset in microeco package to try this function again with the command `data(dataset)`. If you run `print(dataset)`, you can see their is a rep_fasta  element in the object. If you are not sure where is the problem in your result, please send me your data and steps, I will try to repeat it. The function has been tested and checked in the v0.11.0 release.

Best
Chi

**Comment by Wellington9023** [comment]
It works. I ran the old code before so it happened to a problem. Thanks for your help!

**Comment by hshepherdeco** [comment]
Hi,

I'm also facing this same issue (Error in t1$cal_tax4fun2_FRI() : Please first run cal_tax4fun2 !). I'm having this issue with both my own data and the test data (7.2 in the tutorial). All the other stages in the code work, including the cal_tax4fun2 function, so i'm unsure how to solve the issue. Could you advise how this was solved before?

thanks! this package is fantastic otherwise,

Harry

**Comment by ChiLiubio** [comment]
Hi. Which version of microeco package are you using? A bug is in the version v0.11.0 and has been fixed in the current v0.12.0.
I guess this comes from the bug. Please update the package and try again. Thanks.

Chi

**Comment by hshepherdeco** [comment]
That solved it, thanks a lot for that!

Harry
