### ISSUE TITLE
trans_rarefy error

### ISSUE THREAD

**Issue by apoosakkannu** [ChiLiubio/microeco#159]
Hi, I tried to do rarefaction analysis for my dataset 

# trans_rarefy class
t1 <- trans_rarefy$new(dataset1, alphadiv = "Shannon", depth = c(0, 10, 50, 500, 2000, 4000, 6000, 8000))

But i get the following error,

Error in data.frame(SampleID = samplenames, seqnum = i, inter_res) :
arguments imply differing number of rows: 349, 1, 346

I hereby attached the dataset for your reproducibility.

[dataset1.rdata.zip](https://github.com/ChiLiubio/microeco/files/9936710/dataset1.rdata.zip)

please let me know where it is going wrong, thanks in advance.

**Comment by ChiLiubio** [comment]
Hi,

This issue comes from lower sequence number of some samples. I find the lowest number of sample is 113 with the command `range(dataset1$sample_sums())`. The original design of this function does not allow a lower depth number than the samples. So it throw this error. So the current temporal solution is filter some samples with low depth.
```
library(magrittr)
dataset1$otu_table %<>% .[, dataset1$sample_sums() > 10000]
dataset1$tidy_dataset()
# then run your steps
```
Another solution is to update the package from github. I have updated mecodev in github. The new version can skip a rarefaction if a depth is higher than the sample reads number.

Best,
Chi

**Comment by apoosakkannu** [comment]
Thanks.
