### ISSUE TITLE
Question about Trans_network part for t1$cal_node_type()

### ISSUE THREAD

**Issue by Jin-1106** [ChiLiubio/microeco#17]
Hi Chi,

See you again.  Now I have 3 group samples and I am doing network analysis separately, but there is a tiny question about function of t1$cal_node_type() for last group, this group has only 5 samples and less OTU, the result following:

![Screenshot from 2021-03-11 12-18-12](https://user-images.githubusercontent.com/77013101/110735495-dc579580-8264-11eb-9887-2abb6b1e5000.png)
Do you have any suggestion to avoid this error?  Thanks.

Best,
JIN Jing

**Comment by ChiLiubio** [comment]
Hi JIN,

The error may come from the Zi value missing in the intermediate calculation because of the particularity of this network. Can you debug this by running the several functions in this step? This part of code is very easy to check. You can find the function module_roles() in the trans_network.R file and try to run this code line by line to check the data abnormal. Please remember to delete the private$ in front of the functions. If not feasible, please send me the t3 Rdata to my email.

Best
Chi

**Comment by ChiLiubio** [comment]
Hi @Jin-1106 

Could you send me both t3 and t1 Rdata object to my email? Maybe it is a little tricky to debug these issues.

Chi

**Comment by Jin-1106** [comment]
Hi @ChiLiubio 

Sure, I' ve sent them to you. Thanks.

Best,
JIN Jing

**Comment by ChiLiubio** [comment]
Hi, @Jin-1106 

Please use the following command: save(t1, file = "t1.RData") to save t1 and t3 and send me the t1.RData and t3.RData. Thus, I can repeat your issue normally.

Chi

**Comment by Jin-1106** [comment]
Hi @ChiLiubio 

Yes, I recall you helped me with this format last time. Send you again. Thanks.

Best,
Jin Jing

**Comment by ChiLiubio** [comment]
Hi, @Jin-1106 

I have updated the code in github. Please reinstall the package and try again. The SparCC issue in t1 is a bug on the file format. The issue in t3 comes from the network property. No available Zi value can be obtained from this network. I have add a warning inside the code.

Chi

**Comment by Jin-1106** [comment]
Hi, @ChiLiubio 

Thank you for always prompt reply. Now it' s done.

Best,
Jin Jing
