### ISSUE TITLE
 intersection plots (venn class)

### ISSUE THREAD

**Issue by jamorillo** [ChiLiubio/microeco#202]
Hello, 
I am trying to prepare a pannel figure including some plots that I got using microeco.
But I have an issue with the “intersection plots” (venn class):
a <- t1$plot_bar() 
> class(a)
[1] "aplot"

An object “aplot” is not recognized by graphic packages like patchwork, for instance.
How can I convert it to a ggplot2 object?
Thanks!
jose

**Comment by ChiLiubio** [comment]
Hi. It can not be directly converted to ggplot2, because it is comprised of seperate ggplot2 object. If you want to change the plot, you should manipulate specific element. You will understand when you try to run this:
```
library(microeco)
data(dataset)
t1 <- dataset$merge_samples(use_group = "Group")
t1 <- trans_venn$new(dataset = t1, ratio = "numratio")
t2 <- t1$plot_bar()
t2[[1]]
t2[[2]]
```
Each element in `t2` is a ggplot2 object. You can change t2[[1]] or t2[[2]] as you want like other ggplot2 object. When t2 is printed, the axis can be aligned automatically. To save `t2`, you can use `aplot::ggsave` function. Please feel free to tell me if you have other different operation not like this.

Chi

**Comment by jamorillo** [comment]
Now I see.
Thanks, very useful!
