### ISSUE TITLE
filter_taxa

### ISSUE THREAD

**Issue by jamorillo** [ChiLiubio/microeco#204]
Hello again, 

In the tutorial, it is shown how to filter ASVs from a microtable object using this example, but I get this error:

> dataset_filter <- clone(dataset)

> dataset_filter$filter_taxa(rel_abund = 0.0001, freq = 0.1)
Error: attempt to apply non-function

Besides, I can´t fin the documentation of the "filter_taxa" funtion, in order to learn more about the arguments. Asking to R:
?filter_taxa 
shows the filter_taxa of the phyloseq package; is it the same funcion?
(it is not the same function apparently, because the arguments are different)

In this regard, for example, how could I perform custom filters, like:

1) filter out all ASVs that are not present in 100% of the samples, 

or with two conditions, like:

2) filter out all ASVs that are not present in 100% of samples of the Group "IW", AND are also not detectable in the rest of groups.

I need this kind of filters to prepare figures of site-specific ASVs.
Would be nice to do this using Microeco package, otherwise, do you recommend me any alternative?

thanks again for the responses, and for developing this great package!
jose

**Comment by ChiLiubio** [comment]
Hi. The most probable reason should come from the old package version. Please first update your microeco package. Then run `?microtable`, you can see filter_taxa function in the document. Even though you updat your package, you can not use filter_taxa via `dataset_filter <- clone(dataset)` because dataset is created with old package version and not filter_taxa function in the dataset object as I write (https://chiliubio.github.io/microeco_tutorial/intro.html#r6-class). 
So you should recreate it.
```
dataset_filter <- microtable$new(otu_table = dataset$otu_table, sample_table = dataset$sample_table, tax_table = dataset$tax_table)
```
To filter feature that not in 100% of samples, please use the sample number in `freq`.
```
dataset_filter$filter_taxa(freq = nrow(dataset_filter$sample_table))
```
If different groups are needed to operate separately, please split the dataset like this (https://chiliubio.github.io/microeco_tutorial/basic-class.html#subset-of-samples). Then use filter_taxa function as you want.

Chi

**Comment by jamorillo** [comment]
Hello. Solved. The problem with filter_taxa was the version of the package, true. 
Thank you again for the help!
