### ISSUE TITLE
An Error in trans_env$cal_diff (), method = "KW_dunn"

### ISSUE THREAD

**Issue by sdhorse** [ChiLiubio/microeco#261]
Dear, Dr. Liu
When I choose non-parametric tests for multiple comparisons, i.e. method = "KW_dunn":
t1$cal_diff(method = "KW_dunn", group = "Group", p_adjust_method = "none")
After plotting by t1$plot_diff (), it was found that the difference letters are sometimes denoted by “a” for larger values and sometimes by “b” for larger values (see attached figure). In addition, the t1$res_diff () run results in an alphabetical order in the “Group” column, not in a customized order.
![微信截图_20230720110038](https://github.com/ChiLiubio/microeco/assets/54975534/133b0468-33cc-4593-93fc-7ea4a92d9cc8)

**Comment by ChiLiubio** [comment]
Hi. 
Yes. I find it! The issue comes from unordered comparison groups of dependent dunnTest function of FSA package. I have fixed it in the updated github package by adding a checking step. Now the groups are ordered by the median values from high to low. Please reinstall the package from the github and try again.
Thanks for your finding!

Best
Chi
