### ISSUE TITLE
Error in cal_spec_func(fungi_database="FUNGuid"

### ISSUE THREAD

**Issue by AlbertoBernacchi** [ChiLiubio/microeco#392]
Hi there,
while trying to perform an analysis using FUNGuild, I received the following message "Error in if (tax1[j, i] %in% use_database[, "taxon"]) { : 
argument is of length zero.
Do you have any tip on how to overcome this problem? 
Thank you.
Alberto

**Comment by ChiLiubio** [comment]
Hi. 
Could you please attach your data and code so that I can reproduce your issue? To save the microtable object, please follow the steps in the tutorial (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function) and attach the compressed object.
Chi

**Comment by MarCarreras** [comment]
Hi, 
I have the same problem trying to perform FUNGuild., I also recieved the following message "Error in if (tax1[j, i] %in% use_database[, "taxon"]) { : 
[METADATA_VITEC_FUNGI.xlsx](https://github.com/user-attachments/files/17657687/METADATA_VITEC_FUNGI.xlsx)
[OTU_TABLE_VITEC_FUNGI.xlsx](https://github.com/user-attachments/files/17657688/OTU_TABLE_VITEC_FUNGI.xlsx)
argument is of length zero"
I attach my three excel data to creat microeco object, and the script that I am using. 
Thank you so much!
Mar

[METADATA_VITEC_FUNGI.xlsx](https://github.com/user-attachments/files/17657697/METADATA_VITEC_FUNGI.xlsx)
[OTU_TABLE_VITEC_FUNGI.xlsx](https://github.com/user-attachments/files/17657698/OTU_TABLE_VITEC_FUNGI.xlsx)
[TAXA_TABLE_VITEC_FUNGI.xlsx](https://github.com/user-attachments/files/17657699/TAXA_TABLE_VITEC_FUNGI.xlsx)

Script:
# Load the microeco package again
library(microeco)
library(readxl)
library(dplyr)
library(magrittr)
library(openxlsx)
library(ggplot2)
library(tidyr)
library(openxlsx)
library(writexl)

# Set the path to the OTU table
otu_mat<- read_excel("OTU_TABLE_VITEC_FUNGI.xlsx")
head(otu_mat)
# Set the path to the TAXONOMY table
tax_mat<- read_excel("TAXA_TABLE_VITEC_FUNGI.xlsx")
##make the taxonomic information unified (unify the taxonomic prefix)
#tax_mat %<>% tidy_taxonomy   (triga molt temps, mirar-ho!)
# Set the path to the SAMPLES table
sample_mat <- read_excel("METADATA_VITEC_FUNGI.xlsx")
head(sample_mat)

# Preparing tables to be a phyloseq/microeco object
otu_mat <- otu_mat %>%
  tibble::column_to_rownames("otu") 
samples_df <- sample_mat %>% 
  tibble::column_to_rownames("sample") 
tax_df <- as.data.frame(tax_mat)

# Standardize row names in OTU and taxonomy tables
rownames(otu_mat) <- rownames(tax_df)
# Check if row names match now
identical(rownames(otu_mat), rownames(tax_mat))
# Create MICROECO object
dataset <- microtable$new(otu_table = otu_mat)
dataset <- microtable$new(otu_table = otu_mat, sample_table = samples_df)
dataset <- microtable$new(sample_table = samples_df, otu_table = otu_mat, tax_table = tax_df)
dataset$otu_table
dataset$sample_table
dataset$tax_table
dataset
#microtable-class object:
#sample_table have 70 rows and 15 columns
#otu_table have 12397 rows and 70 columns
#tax_table have 12397 rows and 7 columns

# Filter some taxa considered pollution ## this will remove the lines containing the taxa word regardless of taxonomic ranks 
#dataset$filter_pollution(taxa = c("mitochondria", "chloroplast"))

#filtramos tambien los UNCLASSIFIED BACTERIA (kingdom) & UNCLASSIFIED ARCHAEA (kingdom) & UNASSIGNED
dataset$filter_pollution(taxa = c("Unassigned", "Viridiplantae", "Chromista", "Metazoa", "Alveolata", "Ichthyosporia", "Protozoa", "Rhizaria"))
#Total 2973 features are removed from tax_table 

# Rarefaction by minimum reads - mirar el minim i posarlo a sample size
dataset$sample_sums() %>% range  #[1] 43375 74825
dataset$rarefy_samples(sample.size = 30000) 
#258 features are removed because they are no longer present in any sample after random subsampling ...
#258 taxa with 0 abundance are removed from the otu_table ...
dataset$sample_sums() %>% range ##check the sequence numbers

# To make the OTU and sample information consistent across all files in the dataset object, we use function tidy_dataset to trim the dataset.
#dataset$tidy_dataset
dataset
#microtable-class object:
#sample_table have 70 rows and 15 columns
#otu_table have 9166 rows and 70 columns
#tax_table have 9166 rows and 7 columns

###### FAPROTAX

library(microeco)
library("rcompanion")
dataset
f1_dataset <- trans_func$new(dataset)

f1_dataset$cal_spe_func(prok_database = "FAPROTAX")
f1_dataset$res_spe_func
f1_dataset$cal_spe_func_perc(abundance_weighted = TRUE)
f1_dataset$res_spe_func_perc
write.xlsx(f1_dataset$res_spe_func_perc, "OUTPUT/faprotax_table_vitec.xlsx", rowNames = FALSE)

**Comment by ChiLiubio** [comment]
Hi @MarCarreras 
The reason is the taxonomic information table has no Species column. It can be solved by adding a column like the following code shows. I also found the rownames of otu_table and tax_table in the dataset is not the ASV names, so I also changed the code to make it better.
```
library(microeco)
library(readxl)
library(dplyr)
library(magrittr)
library(openxlsx)
library(ggplot2)
library(tidyr)
library(openxlsx)
library(writexl)
# Set the path to the OTU table

otu_mat<- read_excel("OTU_TABLE_VITEC_FUNGI.xlsx")
head(otu_mat)
# Set the path to the TAXONOMY table

tax_mat<- read_excel("TAXA_TABLE_VITEC_FUNGI.xlsx")
##make the taxonomic information unified (unify the taxonomic prefix)
#tax_mat %<>% tidy_taxonomy (triga molt temps, mirar-ho!)
# Set the path to the SAMPLES table

sample_mat <- read_excel("METADATA_VITEC_FUNGI.xlsx")
head(sample_mat)
# Preparing tables to be a phyloseq/microeco object

otu_mat <- otu_mat %>%
tibble::column_to_rownames("otu")

samples_df <- sample_mat %>% tibble::column_to_rownames("sample")
# tax_df <- as.data.frame(tax_mat)
tax_df <- tax_mat %>% tibble::column_to_rownames("otu")

# Create MICROECO object

dataset <- microtable$new(otu_table = otu_mat)
dataset <- microtable$new(otu_table = otu_mat, sample_table = samples_df)
dataset <- microtable$new(sample_table = samples_df, otu_table = otu_mat, tax_table = tax_df)
dataset$otu_table
dataset$sample_table
dataset$tax_table
dataset
#microtable-class object:
#sample_table have 70 rows and 15 columns
#otu_table have 12397 rows and 70 columns
#tax_table have 12397 rows and 7 columns
# Filter some taxa considered pollution ## this will remove the lines containing the taxa word regardless of taxonomic ranks

#dataset$filter_pollution(taxa = c("mitochondria", "chloroplast"))

#filtramos tambien los UNCLASSIFIED BACTERIA (kingdom) & UNCLASSIFIED ARCHAEA (kingdom) & UNASSIGNED
# dataset$filter_pollution(taxa = c("Unassigned", "Viridiplantae", "Chromista", "Metazoa", "Alveolata", "Ichthyosporia", "Protozoa", "Rhizaria"))
dataset$tax_table %<>% .[.$Kingdom == "Fungi", ]
dataset$tidy_dataset()
#Total 2973 features are removed from tax_table
# Rarefaction by minimum reads - mirar el minim i posarlo a sample size

dataset$sample_sums() %>% range #[1] 43375 74825
dataset$rarefy_samples(sample.size = 30000)
#258 features are removed because they are no longer present in any sample after random subsampling ...
#258 taxa with 0 abundance are removed from the otu_table ...
dataset$sample_sums() %>% range ##check the sequence numbers
# To make the OTU and sample information consistent across all files in the dataset object, we use function tidy_dataset to trim the dataset.

#dataset$tidy_dataset
dataset
#microtable-class object:
#sample_table have 70 rows and 15 columns
#otu_table have 9166 rows and 70 columns
#tax_table have 9166 rows and 7 columns


library(microeco)
library("rcompanion")

dataset$tax_table$Species <- ""

f1_dataset <- trans_func$new(dataset)

f1_dataset$cal_spe_func()
f1_dataset$res_spe_func
f1_dataset$cal_spe_func_perc(abundance_weighted = TRUE)
f1_dataset$res_spe_func_perc
```

**Comment by MarCarreras** [comment]
Thank you so much @ChiLiubio, it works perfectly!
