### ISSUE TITLE
Error in rbind(deparse.level, ...) :    numbers of columns of arguments do not match

### ISSUE THREAD

**Issue by wskaerc** [ChiLiubio/microeco#394]
Dear Chi,

I've encountered this error message when analyzing my dataset using the trans_diff function for LEfSe.
> dataset <- microtable$new(sample_table = sample_table,
                     otu_table = feature_table,
                   tax_table = tax_table)
> dataset
microtable-class object:
sample_table have 361 rows and 17 columns
otu_table have 1985 rows and 361 columns
tax_table have 1985 rows and 7 columns

> lefse <- trans_diff$new(dataset = dataset,
                         method = "lefse",
                         p_adjust_method = "fdr",
                         group = "site",
                         alpha = 0.1,
                         lefse_subgroup = NULL)
No taxa_abund list found. Calculate relative abundance with cal_abund function ...
The result is stored in object$taxa_abund ...
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match

Could kindly tell me what went wrong?

Thank you
[test_data.zip](https://github.com/user-attachments/files/16571656/test_data.zip)

**Comment by ChiLiubio** [comment]
Hi. I found the reason is that when there is only one feature (Fungi) in the Kingdom abundance table, the normalization step returns back a table with an abnormal format. I have fixed it. Please reinstall the package (v1.9.0) from github and try again. Thanks for your report to make this method robust.
I also found there is no prefix in your tax_table, which can cause errors in the visualization of lefse cladogram. You can use the following command to tidy it.
```
# this is for v1.9.0, as the tidy_taxonomy function is extended for microtable object. 
# For a version < 1.9.0, it should be dataset$tax_table %<>% tidy_taxonomy
dataset %<>% tidy_taxonomy
dataset$cal_abund()
```

Best,
Chi

**Comment by WongS-K** [comment]
Dear Chi,

Thank you for fixing this error.

**Comment by wskaerc** [comment]
Dear Chi,

Thank you for fixing this error!
