### ISSUE TITLE
Errors using newly generated microtable from phyloseq components

### ISSUE THREAD

**Issue by AngelicaMiraples** [ChiLiubio/microeco#418]
Hi Chi!

I am attempting to use microeco for a few different microbiome applications. I extracted the microtable components from a phyloseq object I frequently use. Both the tax and otu tables were converted to dataframes, resulting in the successful generation of my microtable:

> mp1 <- microtable$new(otu_table = otu_df, sample_table = sam, tax_table = tax_df, phylo_tree = tree)
> mp1
microtable-class object:
sample_table have 26 rows and 6 columns
otu_table have 395 rows and 26 columns
tax_table have 395 rows and 7 columns
phylo_tree have 395 tips

Two functions I'm trying to use but obtain errors for are 1) trans_venn and 2) trans_diff.
1) trans_venn error
`tmp <- mp1$merge_samples("PlantTissue")`
Error in rowsum.default(t(otu_table), as.factor(as.character(sample_table[,  : 
  incorrect length for 'group'

2) trans_diff error 
`t1 <- trans_diff$new(dataset = mp1, method = "lefse", group = "PlantTissue", alpha = 0.01, lefse_subgroup = NULL)`
Error in xtfrm.data.frame(x) : cannot xtfrm data frames

I suspect it may be due to the structure of the individual components of the microtable, but have not resolved either issues. 

Any suggestions would be appreciated.

Best,
Angelica

**Comment by ChiLiubio** [comment]
Hi Angelica,
First, try using the `phyloseq2meco` function from the file2meco package to convert your phyloseq object and obtain `mp1`, and then check if the error is still there. This will help determine if the issue is related to an unusual data format. If the problem continues, please attach the `mp1` data for further examination. To save it, please follow the steps in the tutorial (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function) and attach the compressed object.

Best,
Chi

**Comment by AngelicaMiraples** [comment]
Hi Chi, 

The `phyloseq2meco` function worked. Super easy fix. Thank you for your help!

Best,
A
