### ISSUE TITLE
lefse Cladogram running forever

### ISSUE THREAD

**Issue by alisr7** [ChiLiubio/microeco#43]
Hi Chi,

I have an issue with the cladogram of the differential features, it keeps running forever (more than 48 hours) I had to stop it. I ran it with bacteria without any issue but with fungi it is showing it is still running (no errors). the only difference between bacteria and fungi is that I have a phylogenetic tree included in the bacteria microtable, I am not sure why the fungi cladogram is not working? please let me know if you have any suggestions,
Thanks,
Ali

**Comment by ChiLiubio** [comment]
Hi

Do you have uniform format in your fungi taxonomy table, including the prefix and the uncultured/unknown... names? The cladogram have a strict requirement on the names in taxonomy table. It has no matter with the phylognetic tree. You can use tidy_taxonomy to clean the table. There is an previous Issue that have same problem with you. It may be useful. Please have a look and try. Feel free to tell me if it does not work.

Best
Chi

**Comment by alisr7** [comment]
Hi Chi,

Sorry for my late reply, I made sure my taxonomy table is uniform and used tidy_taxonomy but still having the same problem, I am not sure what is the reason.
Best,
Ali

**Comment by ChiLiubio** [comment]
Hi @alisr7 

Could you please send me your data and scripts? I need run the steps to find out the reason.

**Comment by alisr7** [comment]
Hi Chi,
I sent you the files to your email,
Best,
Ali

**Comment by ChiLiubio** [comment]
Hi @alisr7 

The problem comes from a taxa with an inconsistent taxonomy: "k__Fungi|p__Basidiomycota|c__Agaricomycetes|o__Cantharellales|f__Cantharellales_fam_Incertae_sedis|g__Minimedusa".
In the lefse running, the code filter "........|f__Cantharellales_fam_Incertae_sedis" as it has a suffix Incertae_sedis. So in the cladogram plotting, the taxa "g__Minimedusa" can not find its parent i.e. "f__Cantharellales_fam_Incertae_sedis".
Now, the updated code also filter the taxa with those unidentified taxonomy in the cladogram plotting function. Please try to reinstall the package from the github version and rerun the whole scripts of lefse part.
Any suggestion will be welcome.

Best
Chi

**Comment by alisr7** [comment]
Hi Chi,

I reinstalled the package, and ran the lefse scripts part but still having the same issue.
Thanks,
Ali

**Comment by ChiLiubio** [comment]
Hi @alisr7 

I have checked it again. It is ok. Here is my steps.
[R_20210710.zip](https://github.com/ChiLiubio/microeco/files/6794717/R_20210710.zip)

Best
Chi

**Comment by alisr7** [comment]
Hi Chi,

Thanks a ton for your help, I redid the installation of the microeco package but this time I added the 'force = TRUE' argument, and it is working now. I guess it was skipping the reinstall process.
Thanks,
Ali
