### ISSUE TITLE
trans_abund$new Error in if (ntaxa_use > sum(mean_abund > show))

### ISSUE THREAD

**Issue by nweerasu** [ChiLiubio/microeco#50]
Hello!

I'm running into this error: 
Error in if (ntaxa_use > sum(mean_abund > show)) { : 
  missing value where TRUE/FALSE needed

I don't know if it's related to my actual data, but it seems like the if statement is missing the else, which is what R is looking for when I calculate the trans_abund for my heatmaps.

Let me know if you need some kind of reprex. Thanks!
Nimalka 

Line reference:
https://github.com/cran/microeco/blob/63d9b5b3ab09850fd24fc021565c278154da8e24/R/trans_abund.R#L97

**Comment by ChiLiubio** [comment]
Hi,
Could you save and send me your data? Thus I can repreat your error and judge where the issue comes from.

Chi

**Comment by ChiLiubio** [comment]
Hi, @nweerasu 
The issue comes from two samples with 0 abudance in all the taxa of otu_table from dataset.ss.notsh. Under this situation, using dataset.ss.notsh$cal_abund() can generate NaN in taxa_abund though no error occur in this step. Then those NaN can lead to errors in the abundance mean calculation in taxa abundance plotting. In the previous version, the 0 abundance checking is only implemented in the microtable$new part to check the input otu_table. Now, I also  add this checking to remove the samples and taxa with 0 abundance in the tidy_dataset() function. It is ok now. I have updated the code in github. So try to reinstall the microeco package from github and run your codes again. Please feel free to tell me if something is stuck.

Chi

**Comment by nweerasu** [comment]
Worked perfectly, thank you very much!
