### ISSUE TITLE
Problem in trans_abund$new

### ISSUE THREAD

**Issue by mcordobaa** [ChiLiubio/microeco#9]
Hi!

Thanks for creating this package.

I have a little problem when I try to use this function:  t1 = trans_abund$new(dataset = dataset, taxrank = "Phylum", ntaxa = 10)

the output is: Error: id variables not found in data: Taxonomy

I don't know what it means.
I do this before: 

physeq= qza_to_phyloseq (
  features="table.qza",
  tree="fasttree-tree-rooted.qza",
  taxonomy="taxonomy.qza",
  metadata = "metadata_qiime.txt"
)
dataset <- phyloseq2meco(physeq)
dataset
#output:

microtable class:
sample_table have 32 rows and 4 columns
otu_table have 15427 rows and 32 columns
tax_table have 15427 rows and 7 columns
phylo_tree have 15427 tips

Thanks for You help!

**Comment by ChiLiubio** [comment]
Have you calculated taxonomic abundance using cal_abund function? see the tutorial. If yes, you can see the information when you print dataset. If this does not work, please send me the dataset.RData to my email (liuchi0426@126.com) to check it. Otherwise, I cannot repreat your error and find out the solutions. I suggest you save the dataset using command: save(dataset, file = "dataset.RData") .

**Comment by mcordobaa** [comment]
Thank you so much.
It was my error. I didn't calculate cal_ abund. 
I did this and now I have very useful plots.

Thank you, again.
